application: main
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /working\.gif
  upload: working\.gif
  static_files: working.gif

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
